# Dependencies
markdown:         kramdown
highlighter:         rouge
# redcarpet:
#   extensions: 	["strikethrough"]

# Permalinks
permalink:        pretty

# Setup
title:            Aram Bhusal
tagline:          'code, rails, ruby, python, NLP, stories, poetry, fiction'
url:              http://aram.io
paginate:         0
baseurl:          ""

author:
  name:           Aram
  url:            https://twitter.com/phoenixwizard

# Custom vars
version:          1.0.0
github:
  repo:           github.com/phoenixwizard/aram

pages_list:
  Portfolio: '/portfolio/'

gems:
  - jekyll-redirect-from